import puppeteer, { type PDFOptions } from "puppeteer";
import { logger } from "./logger";

export async function generatePdf(html: string, options: PDFOptions = {}) {
  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage();
    
    // Set content and wait for it to be loaded
    await page.setContent(html, { waitUntil: "networkidle0" as any });
    
    // Generate PDF buffer
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20px", right: "20px", bottom: "20px", left: "20px" },
      ...options,
    });
    
    return pdfBuffer;
  } catch (error) {
    logger.error("Failed to generate PDF:", error);
    throw error;
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

export function generateReportHtml(title: string, headers: string[], rows: any[][]) {
  const tableHeaders = headers.map(h => `<th style="text-align: left; padding: 12px; border-bottom: 2px solid #eee; font-size: 12px; text-transform: uppercase; color: #666;">${h}</th>`).join("");
  const tableRows = rows.map(row => `
    <tr>
      ${row.map(cell => `<td style="padding: 12px; border-bottom: 1px solid #f5f5f5; font-size: 13px; color: #333;">${cell}</td>`).join("")}
    </tr>
  `).join("");

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; margin: 40px; color: #333; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; border-bottom: 4px solid #2563eb; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: 900; color: #2563eb; }
        .report-info { text-align: right; }
        .report-title { font-size: 28px; font-weight: 900; margin-bottom: 10px; color: #111; }
        .report-meta { font-size: 12px; color: #666; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
        .summary-box { background: #f8fafc; padding: 20px; border-radius: 12px; margin-bottom: 30px; display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }
        .summary-item { text-align: center; }
        .summary-label { font-size: 10px; text-transform: uppercase; color: #64748b; font-weight: 900; margin-bottom: 5px; }
        .summary-value { font-size: 20px; font-weight: 900; color: #1e293b; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo text-blue-600">Global College</div>
        <div class="report-info">
          <div class="report-meta">Date: ${new Date().toLocaleDateString()}</div>
          <div class="report-meta">Generated by Admin Panel</div>
        </div>
      </div>

      <h1 class="report-title">${title}</h1>
      
      <table>
        <thead>
          <tr>${tableHeaders}</tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>

      <div class="footer">
        © ${new Date().getFullYear()} Global College of Emerging Technologies - Official Administrative Report
      </div>
    </body>
    </html>
  `;
}
