import * as zod from "zod";
import { Request, Response, Router, type IRouter } from "express";
import { db, entryRecordsTable, usersTable, enrollmentsTable, coursesTable, paymentsTable } from "@workspace/db";
import { eq, and, ilike, or, desc, sql } from "drizzle-orm";
import { AppError } from "../lib/auth";
import { logger } from "../lib/logger";
import { catchAsync } from "../middleware/error";
import { authenticate, authorize, AuthRequest } from "../middleware/auth";

const router: IRouter = Router();

// Validation schemas
const CreateEntryRecordSchema = zod.object({
  studentName: zod.string().min(1, "Student name is required"),
  histNo: zod.string().default(""),
  course: zod.string().min(1, "Course is required"),
  admissionDate: zod.string().default(""),
  duration: zod.string().default(""),
  receiptNo: zod.string().default(""),
  amount: zod.number().default(0),
  month: zod.string().min(1, "Month is required"),
  isAutoGenerated: zod.boolean().default(false),
  userId: zod.number().optional(),
});

const UpdateEntryRecordSchema = CreateEntryRecordSchema.partial();

/**
 * @route GET /api/v1/entry-records
 * @desc Get entry records with optional search and filtering
 * @access Private (Admin, Teacher)
 */
router.get(
  "/entry-records",
  authenticate,
  authorize("admin", "teacher"),
  catchAsync(async (req: AuthRequest, res: Response) => {
    const { search, month } = req.query as any;
    
    let conditions = [];
    
    // Search across student name, course, or hist no
    if (search && search.trim()) {
      const searchTerm = search.trim();
      conditions.push(
        or(
          ilike(entryRecordsTable.studentName, `%${searchTerm}%`),
          ilike(entryRecordsTable.course, `%${searchTerm}%`),
          ilike(entryRecordsTable.histNo, `%${searchTerm}%`)
        )
      );
    }
    
    // Filter by month
    if (month && month.trim()) {
      conditions.push(ilike(entryRecordsTable.month, `%${month.trim()}%`));
    }

    const entryRecords = await db
      .select({
        id: entryRecordsTable.id,
        studentName: entryRecordsTable.studentName,
        histNo: entryRecordsTable.histNo,
        course: entryRecordsTable.course,
        admissionDate: entryRecordsTable.admissionDate,
        duration: entryRecordsTable.duration,
        receiptNo: entryRecordsTable.receiptNo,
        amount: entryRecordsTable.amount,
        month: entryRecordsTable.month,
        isAutoGenerated: entryRecordsTable.isAutoGenerated,
        userId: entryRecordsTable.userId,
        createdAt: entryRecordsTable.createdAt,
      })
      .from(entryRecordsTable)
      .where(conditions.length > 0 ? and(...conditions) : undefined)
      .orderBy(desc(entryRecordsTable.createdAt));

    return res.json(entryRecords);
  })
);

/**
 * @route POST /api/v1/entry-records
 * @desc Create a new entry record
 * @access Private (Admin)
 */
router.post(
  "/entry-records",
  authenticate,
  authorize("admin"),
  catchAsync(async (req: AuthRequest, res: Response) => {
    const validation = CreateEntryRecordSchema.safeParse(req.body);
    
    if (!validation.success) {
      throw new AppError("Validation failed: " + validation.error.issues.map(i => i.message).join(", "), 400);
    }

    const data = validation.data;
    
    const [entryRecord] = await db
      .insert(entryRecordsTable)
      .values(data)
      .returning();

    logger.info(`Entry record created: ${entryRecord.id} - ${entryRecord.studentName}`);
    
    return res.status(201).json(entryRecord);
  })
);

/**
 * @route PUT /api/v1/entry-records/:id
 * @desc Update an entry record
 * @access Private (Admin)
 */
router.put(
  "/entry-records/:id",
  authenticate,
  authorize("admin"),
  catchAsync(async (req: AuthRequest, res: Response) => {
    const id = parseInt(req.params.id as string);
    if (isNaN(id)) {
      throw new AppError("Invalid entry record ID", 400);
    }

    const validation = UpdateEntryRecordSchema.safeParse(req.body);
    
    if (!validation.success) {
      throw new AppError("Validation failed: " + validation.error.issues.map(i => i.message).join(", "), 400);
    }

    const data = validation.data;
    
    const [entryRecord] = await db
      .update(entryRecordsTable)
      .set(data)
      .where(eq(entryRecordsTable.id, id))
      .returning();

    if (!entryRecord) {
      throw new AppError("Entry record not found", 404);
    }

    logger.info(`Entry record updated: ${entryRecord.id} - ${entryRecord.studentName}`);
    
    return res.json(entryRecord);
  })
);

/**
 * @route DELETE /api/v1/entry-records/:id
 * @desc Delete an entry record
 * @access Private (Admin)
 */
router.delete(
  "/entry-records/:id",
  authenticate,
  authorize("admin"),
  catchAsync(async (req: AuthRequest, res: Response) => {
    const id = parseInt(req.params.id as string);
    if (isNaN(id)) {
      throw new AppError("Invalid entry record ID", 400);
    }

    const [deletedRecord] = await db
      .delete(entryRecordsTable)
      .where(eq(entryRecordsTable.id, id))
      .returning();

    if (!deletedRecord) {
      throw new AppError("Entry record not found", 404);
    }

    logger.info(`Entry record deleted: ${deletedRecord.id} - ${deletedRecord.studentName}`);
    
    return res.status(204).send();
  })
);

/**
 * @route POST /api/v1/entry-records/auto-generate/:userId
 * @desc Auto-generate entry record when a student enrolls
 * @access Private (Admin, Teacher) - This will be called internally when enrollment happens
 */
router.post(
  "/entry-records/auto-generate/:userId",
  authenticate,
  authorize("admin", "teacher"),
  catchAsync(async (req: AuthRequest, res: Response) => {
    const userId = parseInt(req.params.userId as string);
    if (isNaN(userId)) {
      throw new AppError("Invalid user ID", 400);
    }

    // Get user details
    const [user] = await db
      .select({
        id: usersTable.id,
        name: usersTable.name,
        regNo: usersTable.regNo,
      })
      .from(usersTable)
      .where(and(eq(usersTable.id, userId), eq(usersTable.role, "student")));

    if (!user) {
      throw new AppError("Student not found", 404);
    }

    // Get student's enrollments with course details
    const enrollments = await db
      .select({
        enrollmentDate: enrollmentsTable.enrolledAt,
        courseTitle: coursesTable.title,
        courseDuration: coursesTable.duration,
      })
      .from(enrollmentsTable)
      .innerJoin(coursesTable, eq(enrollmentsTable.courseId, coursesTable.id))
      .where(eq(enrollmentsTable.userId, userId))
      .orderBy(desc(enrollmentsTable.enrolledAt));

    if (enrollments.length === 0) {
      throw new AppError("No enrollments found for student", 404);
    }

    // Get student's payments for receipt numbers and amounts
    const payments = await db
      .select({
        amount: paymentsTable.amount,
        createdAt: paymentsTable.createdAt,
      })
      .from(paymentsTable)
      .where(and(
        eq(paymentsTable.userId, userId),
        or(
          eq(paymentsTable.status, "approved"),
          eq(paymentsTable.status, "verified")
        )
      ))
      .orderBy(paymentsTable.createdAt);

    // Calculate totals
    const totalAmount = payments.reduce((sum, p) => sum + p.amount, 0);
    const firstEnrollment = enrollments[0];
    const receiptNumbers = payments.map((_, index) => `RCP-${String(index + 1).padStart(3, '0')}`).join(", ");
    
    const currentMonth = new Date().toLocaleDateString("en-GB", { 
      month: "long", 
      year: "numeric" 
    });

    // Create auto-generated entry record
    const [entryRecord] = await db
      .insert(entryRecordsTable)
      .values({
        studentName: user.name,
        histNo: user.regNo || "",
        course: enrollments.map(e => e.courseTitle).join(", "),
        admissionDate: firstEnrollment.enrollmentDate?.toLocaleDateString("en-GB") || "",
        duration: enrollments.map(e => e.courseDuration).join(", "),
        receiptNo: receiptNumbers || "AUTO-GEN",
        amount: totalAmount,
        month: currentMonth,
        isAutoGenerated: true,
        userId: userId,
      })
      .returning();

    logger.info(`Auto-generated entry record for student: ${user.name} (ID: ${userId})`);
    
    return res.status(201).json({
      message: "Entry record auto-generated successfully",
      entryRecord
    });
  })
);

export default router;