import { useState, useEffect } from "react";
import React from "react";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { 
  Plus, 
  Printer, 
  FileText, 
  X, 
  Search, 
  Calendar,
  Edit,
  Trash2,
  Eye,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight
} from "lucide-react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";

// Add API client for authenticated requests
const apiClient = {
  async get(url: string) {
    const token = localStorage.getItem('token') || sessionStorage.getItem('token');
    
    const response = await fetch(url, {
      headers: {
        'Authorization': token ? `Bearer ${token}` : '',
        'Content-Type': 'application/json',
      },
    });
    
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Network error' }));
      throw new Error(errorData.message || `HTTP ${response.status}`);
    }
    
    return await response.json();
  },

  async post(url: string, data: any) {
    const token = localStorage.getItem('token') || sessionStorage.getItem('token');
    
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': token ? `Bearer ${token}` : '',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Network error' }));
      throw new Error(errorData.message || `HTTP ${response.status}`);
    }
    
    return await response.json();
  },

  async put(url: string, data: any) {
    const token = localStorage.getItem('token') || sessionStorage.getItem('token');
    
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Authorization': token ? `Bearer ${token}` : '',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Network error' }));
      throw new Error(errorData.message || `HTTP ${response.status}`);
    }
    
    return await response.json();
  },

  async delete(url: string) {
    const token = localStorage.getItem('token') || sessionStorage.getItem('token');
    
    const response = await fetch(url, {
      method: 'DELETE',
      headers: {
        'Authorization': token ? `Bearer ${token}` : '',
        'Content-Type': 'application/json',
      },
    });
    
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ message: 'Network error' }));
      throw new Error(errorData.message || `HTTP ${response.status}`);
    }
    
    return await response.json();
  }
};

// Types
interface EntryRecord {
  id: number;
  studentName: string;
  histNo: string;
  course: string;
  admissionDate: string;
  duration: string;
  receiptNo: string;
  amount: number;
  month: string;
  createdAt: string;
  isAutoGenerated: boolean;
}

interface NewEntryRecord {
  studentName: string;
  histNo: string;
  course: string;
  admissionDate: string;
  duration: string;
  receiptNo: string;
  amount: number;
  month: string;
}

export default function EntryRecordsPage() {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [editingRecord, setEditingRecord] = useState<EntryRecord | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedMonth, setSelectedMonth] = useState("");
  
  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(20);

  // Add custom print styles to the page
  React.useEffect(() => {
    const style = document.createElement('style');
    style.textContent = `
      @media print {
        /* Page setup */
        @page {
          margin: 2cm 1cm 2cm 1cm;
          size: A4;
        }
        
        /* Force header to repeat on each page */
        .print-header {
          display: table-header-group !important;
          page-break-inside: avoid !important;
          position: fixed !important;
          top: 0 !important;
          left: 0 !important;
          right: 0 !important;
          z-index: 9999 !important;
        }
        
        /* Table header repetition */
        thead {
          display: table-header-group !important;
        }
        
        tbody {
          display: table-row-group !important;
        }
        
        /* Fix table styling */
        .print-table-container table {
          font-size: 10px !important;
          width: 100% !important;
          border-collapse: collapse !important;
        }
        
        .print-table-container th {
          background-color: #6b1a2e !important;
          color: white !important;
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
          page-break-inside: avoid !important;
        }
        
        .print-table-container tr:nth-child(even) {
          background-color: #f8f9fa !important;
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
        }
        
        .entry-records-table {
          box-shadow: none !important;
          border-radius: 0 !important;
        }
        
        /* Ensure content starts below fixed header */
        body {
          padding-top: 150px !important;
        }
        
        /* Page break controls */
        .print-info, .print-table-container {
          page-break-inside: avoid !important;
        }
        
        tr {
          page-break-inside: avoid !important;
        }
      }
    `;
    document.head.appendChild(style);
    return () => document.head.removeChild(style);
  }, []);

  // Reset to first page when search/filter changes
  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, selectedMonth]);

  // Form state
  const [formData, setFormData] = useState<NewEntryRecord>({
    studentName: "",
    histNo: "",
    course: "",
    admissionDate: "",
    duration: "",
    receiptNo: "",
    amount: 0,
    month: new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" }),
  });

  // Fetch entry records
  const { data: entryRecords = [], isLoading, error } = useQuery({
    queryKey: ["/api/entry-records", searchQuery, selectedMonth],
    queryFn: async () => {
      let url = "/api/entry-records";
      const params = new URLSearchParams();
      if (searchQuery) params.append("search", searchQuery);
      if (selectedMonth) params.append("month", selectedMonth);
      if (params.toString()) url += `?${params.toString()}`;
      
      console.log("🔍 Making API call to:", url);
      const token = localStorage.getItem('token') || sessionStorage.getItem('token');
      console.log("🔑 Token exists:", !!token);
      
      const result = await apiClient.get(url);
      console.log("✅ API Response:", result);
      return result;
    },
    staleTime: 30000,
    retry: (failureCount, error: any) => {
      console.error("❌ API Error:", error);
      return failureCount < 2;
    },
  });

  // Create entry record mutation
  const createMutation = useMutation({
    mutationFn: (data: NewEntryRecord) => apiClient.post("/api/entry-records", data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/entry-records"] });
      toast({ title: "✓ Entry record created successfully" });
      resetForm();
    },
    onError: (error: any) => {
      toast({
        title: "Error creating entry record",
        description: error.message,
        variant: "destructive"
      });
    },
  });

  // Update entry record mutation
  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: NewEntryRecord }) =>
      apiClient.put(`/api/entry-records/${id}`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/entry-records"] });
      toast({ title: "✓ Entry record updated successfully" });
      resetForm();
    },
    onError: (error: any) => {
      toast({
        title: "Error updating entry record",
        description: error.message,
        variant: "destructive"
      });
    },
  });

  // Delete entry record mutation
  const deleteMutation = useMutation({
    mutationFn: (id: number) => apiClient.delete(`/api/entry-records/${id}`),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/entry-records"] });
      toast({ title: "✓ Entry record deleted successfully" });
    },
    onError: (error: any) => {
      toast({
        title: "Error deleting entry record",
        description: error.message,
        variant: "destructive"
      });
    },
  });

  const resetForm = () => {
    setFormData({
      studentName: "",
      histNo: "",
      course: "",
      admissionDate: "",
      duration: "",
      receiptNo: "",
      amount: 0,
      month: new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" }),
    });
    setShowForm(false);
    setEditingRecord(null);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.studentName || !formData.course) {
      toast({
        title: "Please fill required fields",
        description: "Student name and course are required",
        variant: "destructive"
      });
      return;
    }

    if (editingRecord) {
      updateMutation.mutate({ id: editingRecord.id, data: formData });
    } else {
      createMutation.mutate(formData);
    }
  };

  const handleEdit = (record: EntryRecord) => {
    setEditingRecord(record);
    setFormData({
      studentName: record.studentName,
      histNo: record.histNo,
      course: record.course,
      admissionDate: record.admissionDate,
      duration: record.duration,
      receiptNo: record.receiptNo,
      amount: record.amount,
      month: record.month,
    });
    setShowForm(true);
  };

  const handleDelete = (id: number) => {
    if (window.confirm("Are you sure you want to delete this entry record?")) {
      deleteMutation.mutate(id);
    }
  };

  const printAllRecords = async () => {
    try {
      // For now, print the currently loaded records
      const allRecords = entryRecords;
      
      if (!Array.isArray(allRecords) || allRecords.length === 0) {
        toast({
          title: "Print Error",
          description: "No records to print",
          variant: "destructive"
        });
        return;
      }

      const printWindow = window.open('', '_blank');
      if (!printWindow) return;

      const currentDate = new Date().toLocaleDateString("en-GB", {
        day: '2-digit',
        month: 'long', 
        year: 'numeric'
      });

      const currentTime = new Date().toLocaleTimeString("en-GB", {
        hour: '2-digit',
        minute: '2-digit'
      });

      // Generate table rows for all records
      const tableRows = allRecords.map((record, idx) => `
        <tr>
          <td class="sr-no">${idx + 1}</td>
          <td class="student-name">${record.studentName}</td>
          <td>${record.histNo || 'N/A'}</td>
          <td>${record.course}</td>
          <td>${record.admissionDate || 'N/A'}</td>
          <td>${record.duration || 'N/A'}</td>
          <td>${record.receiptNo || 'N/A'}</td>
          <td class="amount">Rs. ${record.amount.toLocaleString()}</td>
          <td>${record.month}</td>
          <td>
            <span class="type-badge ${record.isAutoGenerated ? 'type-auto' : 'type-manual'}">
              ${record.isAutoGenerated ? 'AUTO' : 'MANUAL'}
            </span>
          </td>
        </tr>
      `).join('');

      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>Entry Records - GCCS</title>
            <style>
              * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
              }
              
              @page {
                margin: 2cm 1cm 2cm 1cm;
                size: A4 portrait;
                @top-center {
                  content: "GLOBAL COLLEGE OF COMPUTER SCIENCE - STUDENT ENTRY RECORDS REGISTER";
                  font-size: 12px;
                  font-weight: bold;
                  color: #6b1a2e;
                }
              }
              
              body { 
                font-family: 'Arial', sans-serif; 
                background: white;
                color: #000;
                line-height: 1.3;
                padding-top: 0;
              }
              
              /* Fixed header that repeats on all pages */
              .print-header {
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                background: white;
                z-index: 1000;
                page-break-inside: avoid;
                page-break-after: avoid;
                border-bottom: 3px solid #6b1a2e;
                padding: 15px;
                margin-bottom: 20px;
              }
              
              .college-name {
                color: #6b1a2e;
                font-size: 20px;
                font-weight: bold;
                margin-bottom: 3px;
                letter-spacing: 0.5px;
                text-align: center;
              }
              
              .college-subtitle {
                color: #8b1538;
                font-size: 12px;
                margin-bottom: 2px;
                font-style: italic;
                text-align: center;
              }
              
              .document-title {
                color: #6b1a2e;
                font-size: 16px;
                font-weight: bold;
                margin-top: 8px;
                text-decoration: underline;
                text-align: center;
              }
              
              /* Main content starts below fixed header */
              .print-content {
                margin-top: 140px;
                position: relative;
              }
              
              .print-info {
                display: flex;
                justify-content: space-between;
                align-items: flex-start;
                margin-bottom: 15px;
                font-size: 11px;
                color: #666;
                page-break-inside: avoid;
              }
              
              .print-table-container {
                width: 100%;
                overflow: visible;
                page-break-inside: auto;
              }
              
              table { 
                width: 100%; 
                border-collapse: collapse; 
                font-size: 9px;
                margin-bottom: 15px;
                page-break-inside: auto;
              }
              
              /* Table header that repeats on each page */
              thead {
                display: table-header-group;
                page-break-inside: avoid;
                page-break-after: avoid;
              }
              
              tbody {
                display: table-row-group;
              }
              
              th, td { 
                border: 1.5px solid #000; 
                padding: 6px 4px; 
                text-align: left;
                vertical-align: top;
                word-wrap: break-word;
              }
              
              th { 
                background-color: #6b1a2e !important;
                color: white !important;
                font-weight: bold;
                text-align: center;
                font-size: 8px;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
                page-break-inside: avoid;
                page-break-after: avoid;
              }
              
              tr:nth-child(even) {
                background-color: #f8f9fa !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }
              
              tr {
                page-break-inside: avoid;
                page-break-after: auto;
              }
              
              .sr-no {
                text-align: center !important;
                font-weight: bold;
                background-color: #e8f4f8 !important;
                color: #6b1a2e !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
                width: 8%;
              }
              
              .student-name {
                font-weight: bold;
                color: #333;
                width: 18%;
              }
              
              .amount {
                text-align: right !important;
                font-weight: bold;
                color: #2d8f3f;
                width: 12%;
              }
              
              .type-badge {
                display: inline-block;
                padding: 2px 4px;
                border-radius: 3px;
                font-size: 7px;
                font-weight: bold;
                text-align: center;
                width: 8%;
              }
              
              .type-auto {
                background-color: #d4edda !important;
                color: #155724 !important;
                border: 1px solid #c3e6cb;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }
              
              .type-manual {
                background-color: #cce5ff !important;
                color: #004085 !important;
                border: 1px solid #99d6ff;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }
              
              .summary-box {
                border: 2px solid #6b1a2e;
                padding: 8px;
                background-color: #f8f9fa !important;
                display: inline-block;
                min-width: 180px;
                font-size: 10px;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }
              
              .summary-title {
                color: #6b1a2e;
                font-weight: bold;
                font-size: 11px;
                margin-bottom: 4px;
                text-align: center;
              }
              
              .summary-row {
                display: flex;
                justify-content: space-between;
                margin-bottom: 2px;
              }
              
              .print-footer {
                margin-top: 25px;
                border-top: 2px solid #6b1a2e;
                padding-top: 15px;
                display: flex;
                justify-content: space-between;
                font-size: 11px;
                page-break-inside: avoid;
              }
              
              .signature-section {
                text-align: center;
                width: 30%;
              }
              
              .signature-line {
                border-bottom: 2px solid #000;
                margin-top: 25px;
                margin-bottom: 5px;
              }
              
              .signature-label {
                font-weight: bold;
                color: #6b1a2e;
              }
              
              /* Print-specific settings */
              body { 
                -webkit-print-color-adjust: exact; 
                print-color-adjust: exact; 
              }
              
              .print-hidden { 
                display: none !important; 
              }
            </style>
          </head>
          <body>
            <!-- Fixed header that repeats on all pages -->
            <div class="print-header">
              <div class="college-name">GLOBAL COLLEGE OF COMPUTER SCIENCE</div>
              <div class="college-subtitle">Excellence in Technical Education</div>
              <div class="college-subtitle">📍 Address: Main Campus, City • 📞 Phone: +92-XXX-XXXXXXX • 📧 Email: info@gccs.edu.pk</div>
              <div class="document-title">STUDENT ENTRY RECORDS REGISTER</div>
            </div>
            
            <!-- Main content -->
            <div class="print-content">
              <div class="print-info">
                <div>
                  <strong>Generated on:</strong> ${currentDate} at ${currentTime}<br/>
                  <strong>Total Records:</strong> ${allRecords.length}
                  ${selectedMonth ? `<br/><strong>Filtered by:</strong> ${selectedMonth}` : ''}
                  ${searchQuery ? `<br/><strong>Search:</strong> ${searchQuery}` : ''}
                </div>
                <div class="summary-box">
                  <div class="summary-title">Summary</div>
                  <div class="summary-row">
                    <span>Total Students:</span>
                    <span><strong>${allRecords.length}</strong></span>
                  </div>
                  <div class="summary-row">
                    <span>Auto Generated:</span>
                    <span><strong>${allRecords.filter(r => r.isAutoGenerated).length}</strong></span>
                  </div>
                  <div class="summary-row">
                    <span>Manual Entries:</span>
                    <span><strong>${allRecords.filter(r => !r.isAutoGenerated).length}</strong></span>
                  </div>
                  <div class="summary-row">
                    <span>Total Amount:</span>
                    <span><strong>Rs. ${allRecords.reduce((sum, r) => sum + r.amount, 0).toLocaleString()}</strong></span>
                  </div>
                </div>
              </div>

              <div class="print-table-container">
                <table>
                  <thead>
                    <tr>
                      <th class="sr-no">Sr.No</th>
                      <th>Name of Trainee</th>
                      <th>Hist. No.</th>
                      <th>Course</th>
                      <th>Admission Date</th>
                      <th>Duration</th>
                      <th>Fee Rec. No.</th>
                      <th class="amount">Amount</th>
                      <th>Month</th>
                      <th>Type</th>
                    </tr>
                  </thead>
                  <tbody>
                    ${tableRows}
                  </tbody>
                </table>
              </div>
              
              <div class="print-footer">
                <div class="signature-section">
                  <div class="signature-line"></div>
                  <div class="signature-label">Prepared By</div>
                </div>
                <div class="signature-section">
                  <div class="signature-line"></div>
                  <div class="signature-label">Verified By</div>
                </div>
                <div class="signature-section">
                  <div class="signature-line"></div>
                  <div class="signature-label">Principal</div>
                </div>
              </div>
            </div>
          </body>
        </html>
      `);

      printWindow.document.close();
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 500);
      };
      
    } catch (error) {
      console.error('Print error:', error);
      toast({
        title: "Print Error",
        description: "Unable to print records. Please try again.",
        variant: "destructive"
      });
    }
  };

  return (
    <DashboardLayout>
      <div className="pb-12">
        {/* Compact Header */}
        <div className="mb-4">
          <h1 className="text-2xl font-bold text-gray-900 mb-1">📋 Entry Records</h1>
          <p className="text-sm text-gray-600">
            Student admission entry records - Auto-generated on enrollment + Manual entries
          </p>
        </div>

        {/* Debug Info for Authentication */}
        {process.env.NODE_ENV === 'development' && (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-3 mb-4">
            <div className="text-sm text-yellow-800">
              <div className="font-semibold mb-1">🔍 Debug Info:</div>
              <div>Token: {localStorage.getItem('token') ? 'Found in localStorage' : sessionStorage.getItem('token') ? 'Found in sessionStorage' : 'Not found'}</div>
              <div>API URL: {`/api/entry-records`}</div>
              <div>Loading: {isLoading.toString()}</div>
              <div>Error: {error ? (error as any).message || 'Unknown error' : 'None'}</div>
              <div>Records Count: {entryRecords.length}</div>
            </div>
          </div>
        )}

        {/* Compact Controls */}
        <div className="bg-white rounded-lg border border-gray-200 shadow-sm p-4 mb-4">
          <div className="flex flex-wrap items-center gap-3 mb-4">
            <Button 
              onClick={() => setShowForm(true)} 
              className="bg-gradient-to-r from-[#6b1a2e] to-[#8b1538] hover:from-[#5a1628] hover:to-[#7a1432] shadow-md hover:shadow-lg transform hover:scale-105 transition-all duration-200 text-sm py-2 px-4"
            >
              <Plus className="h-4 w-4 mr-2" />
              Add Entry Record
            </Button>
            
            <Button 
              onClick={printAllRecords} 
              variant="outline"
              className="border-[#6b1a2e] text-[#6b1a2e] hover:bg-[#6b1a2e] hover:text-white shadow-md hover:shadow-lg transition-all duration-200 text-sm py-2 px-4"
            >
              <Printer className="h-4 w-4 mr-2" />
              Print All Records
            </Button>

            {entryRecords.length > 0 && (
              <div className="ml-auto bg-gradient-to-r from-blue-50 to-indigo-50 px-3 py-2 rounded-lg border border-blue-200">
                <div className="flex items-center gap-2 text-xs">
                  <div className="flex items-center gap-1">
                    <div className="w-2 h-2 rounded-full bg-emerald-500"></div>
                    <span className="text-gray-600">Auto: {entryRecords.filter(r => r.isAutoGenerated).length}</span>
                  </div>
                  <div className="w-px h-3 bg-gray-300"></div>
                  <div className="flex items-center gap-1">
                    <div className="w-2 h-2 rounded-full bg-blue-500"></div>
                    <span className="text-gray-600">Manual: {entryRecords.filter(r => !r.isAutoGenerated).length}</span>
                  </div>
                  <div className="w-px h-3 bg-gray-300"></div>
                  <span className="font-semibold text-gray-800">
                    Page: Rs. {entryRecords.reduce((sum, r) => sum + r.amount, 0).toLocaleString()}
                  </span>
                </div>
              </div>
            )}
          </div>

          {/* Compact Filters */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-1">
              <Label className="text-xs font-semibold text-gray-700 flex items-center gap-2">
                <Search className="h-3 w-3" />
                Search Students
              </Label>
              <div className="relative">
                <Search className="absolute left-2 top-1/2 transform -translate-y-1/2 h-3 w-3 text-gray-400" />
                <Input
                  type="text"
                  placeholder="Search by name, course, or registration number..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-8 border-gray-300 focus:border-[#6b1a2e] focus:ring-[#6b1a2e] shadow-sm text-sm py-2"
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery("")}
                    className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                  >
                    <X className="h-3 w-3" />
                  </button>
                )}
              </div>
            </div>
            
            <div className="space-y-1">
              <Label className="text-xs font-semibold text-gray-700 flex items-center gap-2">
                <Calendar className="h-3 w-3" />
                Filter by Month
              </Label>
              <div className="relative">
                <Calendar className="absolute left-2 top-1/2 transform -translate-y-1/2 h-3 w-3 text-gray-400" />
                <Input
                  type="text"
                  placeholder="e.g. June 2026"
                  value={selectedMonth}
                  onChange={(e) => setSelectedMonth(e.target.value)}
                  className="pl-8 border-gray-300 focus:border-[#6b1a2e] focus:ring-[#6b1a2e] shadow-sm text-sm py-2"
                />
                {selectedMonth && (
                  <button
                    onClick={() => setSelectedMonth("")}
                    className="absolute right-2 top-1/2 transform -translate-y-1/2 text-gray-400 hover:text-gray-600"
                  >
                    <X className="h-3 w-3" />
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Entry Records Table */}
        <div className="bg-white rounded-lg border border-gray-200 shadow-lg entry-records-table">
          {/* Compact Header */}
          <div className="px-4 py-3 border-b border-gray-200 bg-gradient-to-r from-[#6b1a2e] to-[#8b1538] text-white">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold flex items-center gap-2">
                  <FileText className="h-4 w-4" />
                  Entry Records {selectedMonth && `- ${selectedMonth}`}
                </h2>
                <p className="text-xs text-white/80 mt-0.5">
                  Global College of Computer Science - Official Entry Register
                </p>
              </div>
              <div className="text-right">
                <div className="bg-white/10 px-2 py-1 rounded">
                  <p className="text-xs font-semibold">Total</p>
                  <p className="text-lg font-bold">{entryRecords.length}</p>
                </div>
              </div>
            </div>
          </div>

          <div className="overflow-x-auto">
            {isLoading ? (
              <div className="p-8 text-center">
                <div className="animate-spin h-8 w-8 border-4 border-[#6b1a2e] border-t-transparent rounded-full mx-auto mb-3"></div>
                <p className="text-sm text-gray-600">Loading entry records...</p>
              </div>
            ) : error ? (
              <div className="p-8 text-center">
                <div className="bg-red-50 border border-red-200 rounded-lg p-4 max-w-md mx-auto">
                  <div className="text-red-600 text-sm font-semibold mb-1">Error Loading Records</div>
                  <p className="text-red-700 text-sm">{error.message}</p>
                </div>
              </div>
            ) : entryRecords.length === 0 ? (
              <div className="p-8 text-center">
                <div className="bg-gray-50 border-2 border-dashed border-gray-300 rounded-lg p-6 max-w-md mx-auto">
                  <FileText className="h-12 w-12 mx-auto mb-3 text-gray-300" />
                  <p className="text-sm font-medium text-gray-600 mb-1">No Entry Records Found</p>
                  <p className="text-xs text-gray-500">
                    {searchQuery || selectedMonth ? "Try adjusting your filters" : "Add your first entry record to get started"}
                  </p>
                </div>
              </div>
            ) : (
              <div className="print-table-container">
                <table className="w-full border-collapse text-sm">
                  <thead>
                    <tr className="bg-gradient-to-r from-[#6b1a2e] to-[#8b1538] text-white">
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-16">Sr.No</th>
                      <th className="border border-gray-300 px-3 py-2 text-left font-bold text-xs">Name of Trainee</th>
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-20">Hist. No.</th>
                      <th className="border border-gray-300 px-3 py-2 text-left font-bold text-xs">Course</th>
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-24">Admission Date</th>
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-20">Duration</th>
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-24">Fee Rec. No.</th>
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-24">Amount</th>
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-20">Month</th>
                      <th className="border border-gray-300 px-2 py-2 text-left font-bold text-xs w-16">Type</th>
                      <th className="border border-gray-300 px-2 py-2 text-center font-bold text-xs w-20 print:hidden">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {entryRecords.map((record: EntryRecord, idx: number) => (
                      <tr 
                        key={record.id} 
                        className={`hover:bg-blue-50 transition-colors ${
                          idx % 2 === 0 ? 'bg-gray-50' : 'bg-white'
                        }`}
                      >
                        <td className="border border-gray-300 px-2 py-2 text-center font-bold text-[#6b1a2e] bg-blue-50 text-sm">
                          {idx + 1}
                        </td>
                        <td className="border border-gray-300 px-3 py-2 font-medium text-gray-900 text-sm">
                          {record.studentName}
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center font-medium text-gray-700 text-xs">
                          {record.histNo || 'N/A'}
                        </td>
                        <td className="border border-gray-300 px-3 py-2 text-gray-800 text-sm max-w-xs">
                          <div className="truncate" title={record.course}>
                            {record.course}
                          </div>
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center text-gray-700 text-xs">
                          {record.admissionDate || 'N/A'}
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center text-gray-700 text-xs">
                          {record.duration || 'N/A'}
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center font-medium text-gray-700 text-xs">
                          {record.receiptNo || 'N/A'}
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-right font-bold text-green-700 text-sm">
                          Rs. {record.amount.toLocaleString()}
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center text-gray-700 text-xs">
                          {record.month}
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center">
                          <span className={`inline-flex px-1.5 py-0.5 rounded text-xs font-bold ${
                            record.isAutoGenerated 
                              ? "bg-emerald-100 text-emerald-800 border border-emerald-300" 
                              : "bg-blue-100 text-blue-800 border border-blue-300"
                          }`}>
                            {record.isAutoGenerated ? "AUTO" : "MANUAL"}
                          </span>
                        </td>
                        <td className="border border-gray-300 px-2 py-2 text-center print:hidden">
                          <div className="flex gap-1 justify-center">
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => handleEdit(record)}
                              className="h-6 w-6 p-0 hover:bg-blue-50 border-blue-200"
                              title="Edit record"
                            >
                              <Edit className="h-3 w-3 text-blue-600" />
                            </Button>
                            <Button
                              size="sm"
                              variant="outline"
                              onClick={() => handleDelete(record.id)}
                              className="h-6 w-6 p-0 hover:bg-red-50 border-red-200"
                              title="Delete record"
                            >
                              <Trash2 className="h-3 w-3 text-red-600" />
                            </Button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Simple Footer */}
          {entryRecords.length > 0 && (
            <div className="px-4 py-2 bg-gray-50 border-t border-gray-200 print:block">
              <div className="flex items-center justify-between text-xs text-gray-600">
                <div className="flex items-center gap-3">
                  <span className="font-medium">
                    Showing {entryRecords.length} record{entryRecords.length !== 1 ? 's' : ''}
                  </span>
                  {(searchQuery || selectedMonth) && (
                    <span className="text-blue-600 font-medium">
                      (Filtered results)
                    </span>
                  )}
                </div>
                <div className="hidden print:block text-xs">
                  <p>Generated on: {new Date().toLocaleDateString('en-GB', { 
                    day: '2-digit', 
                    month: 'long', 
                    year: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit'
                  })}</p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Entry Form Modal */}
        {showForm && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
              <div className="border-b border-gray-200 p-4">
                <h3 className="text-lg font-bold text-gray-900">
                  {editingRecord ? "Edit Entry Record" : "Add New Entry Record"}
                </h3>
              </div>

              <form onSubmit={handleSubmit} className="p-6 space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-sm font-medium mb-2 block">
                      Student Name <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      type="text"
                      value={formData.studentName}
                      onChange={(e) => setFormData({ ...formData, studentName: e.target.value })}
                      placeholder="Enter student name"
                      required
                    />
                  </div>
                  
                  <div>
                    <Label className="text-sm font-medium mb-2 block">History Number</Label>
                    <Input
                      type="text"
                      value={formData.histNo}
                      onChange={(e) => setFormData({ ...formData, histNo: e.target.value })}
                      placeholder="Registration number"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-sm font-medium mb-2 block">
                      Course <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      type="text"
                      value={formData.course}
                      onChange={(e) => setFormData({ ...formData, course: e.target.value })}
                      placeholder="Enter course name"
                      required
                    />
                  </div>
                  
                  <div>
                    <Label className="text-sm font-medium mb-2 block">Duration</Label>
                    <Input
                      type="text"
                      value={formData.duration}
                      onChange={(e) => setFormData({ ...formData, duration: e.target.value })}
                      placeholder="e.g., 6 months"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-sm font-medium mb-2 block">Admission Date</Label>
                    <Input
                      type="date"
                      value={formData.admissionDate}
                      onChange={(e) => setFormData({ ...formData, admissionDate: e.target.value })}
                    />
                  </div>
                  
                  <div>
                    <Label className="text-sm font-medium mb-2 block">Amount</Label>
                    <Input
                      type="number"
                      value={formData.amount}
                      onChange={(e) => setFormData({ ...formData, amount: parseInt(e.target.value) || 0 })}
                      placeholder="Fee amount"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label className="text-sm font-medium mb-2 block">Receipt Number</Label>
                    <Input
                      type="text"
                      value={formData.receiptNo}
                      onChange={(e) => setFormData({ ...formData, receiptNo: e.target.value })}
                      placeholder="Receipt number"
                    />
                  </div>
                  
                  <div>
                    <Label className="text-sm font-medium mb-2 block">Month</Label>
                    <Input
                      type="text"
                      value={formData.month}
                      onChange={(e) => setFormData({ ...formData, month: e.target.value })}
                      placeholder="e.g., June 2026"
                    />
                  </div>
                </div>

                <div className="flex gap-3 pt-4">
                  <Button
                    type="submit"
                    disabled={createMutation.isPending || updateMutation.isPending}
                    className="bg-[#6b1a2e] hover:bg-[#5a1628]"
                  >
                    {createMutation.isPending || updateMutation.isPending ? (
                      <>
                        <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                        {editingRecord ? "Updating..." : "Creating..."}
                      </>
                    ) : (
                      <>{editingRecord ? "Update Record" : "Create Record"}</>
                    )}
                  </Button>
                  
                  <Button type="button" variant="outline" onClick={resetForm}>
                    Cancel
                  </Button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}