import { pgTable, text, serial, timestamp, boolean, integer, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { usersTable } from "./users";

export const entryRecordsTable = pgTable("entry_records", {
  id: serial("id").primaryKey(),
  studentName: text("student_name").notNull(),
  histNo: text("hist_no").notNull().default(""),
  course: text("course").notNull(),
  admissionDate: text("admission_date").notNull().default(""),
  duration: text("duration").notNull().default(""),
  receiptNo: text("receipt_no").notNull().default(""),
  amount: integer("amount").notNull().default(0),
  month: text("month").notNull(),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  userId: integer("user_id").references(() => usersTable.id), // Optional reference to actual user
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
}, (table) => {
  return {
    studentNameIdx: index("entry_records_student_name_idx").on(table.studentName),
    courseIdx: index("entry_records_course_idx").on(table.course),
    monthIdx: index("entry_records_month_idx").on(table.month),
    isAutoGeneratedIdx: index("entry_records_is_auto_generated_idx").on(table.isAutoGenerated),
    userIdIdx: index("entry_records_user_id_idx").on(table.userId),
    createdAtIdx: index("entry_records_created_at_idx").on(table.createdAt),
  };
});

export const insertEntryRecordSchema = createInsertSchema(entryRecordsTable).omit({ 
  id: true, 
  createdAt: true, 
  updatedAt: true 
});

export type InsertEntryRecord = z.infer<typeof insertEntryRecordSchema>;
export type EntryRecord = typeof entryRecordsTable.$inferSelect;