/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Test API
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export const getTest = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.default.get(
      `/test`,options
    );
  }

export type GetTestResult = AxiosResponse<void>
